In [1]:
import numpy as np
import pandas as pd

In [2]:
True_news=pd.read_csv('True.csv')
Fake_news=pd.read_csv('Fake.csv')

In [3]:
True_news

title   
0      As U.S. budget fight looms, Republicans flip t...  \
1      U.S. military to accept transgender recruits o...   
2      Senior U.S. Republican senator: 'Let Mr. Muell...   
3      FBI Russia probe helped by Australian diplomat...   
4      Trump wants Postal Service to charge 'much mor...   
...                                                  ...   
21412  'Fully committed' NATO backs new U.S. approach...   
21413  LexisNexis withdrew two products from Chinese ...   
21414  Minsk cultural hub becomes haven from authorities   
21415  Vatican upbeat on possibility of Pope Francis ...   
21416  Indonesia to buy $1.14 billion worth of Russia...   

                                                    text       subject   
0      WASHINGTON (Reuters) - The head of a conservat...  politicsNews  \
1      WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2      WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3      WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4      SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   
...                                                  ...           ...   
21412  BRUSSELS (Reuters) - NATO allies on Tuesday we...     worldnews   
21413  LONDON (Reuters) - LexisNexis, a provider of l...     worldnews   
21414  MINSK (Reuters) - In the shadow of disused Sov...     worldnews   
21415  MOSCOW (Reuters) - Vatican Secretary of State ...     worldnews   
21416  JAKARTA (Reuters) - Indonesia will buy 11 Sukh...     worldnews   

                     date  
0      December 31, 2017   
1      December 29, 2017   
2      December 31, 2017   
3      December 30, 2017   
4      December 29, 2017   
...                   ...  
21412    August 22, 2017   
21413    August 22, 2017   
21414    August 22, 2017   
21415    August 22, 2017   
21416    August 22, 2017   

[21417 rows x 4 columns]

In [4]:
Fake_news

title   
0       Donald Trump Sends Out Embarrassing New Year’...  \
1       Drunk Bragging Trump Staffer Started Russian ...   
2       Sheriff David Clarke Becomes An Internet Joke...   
3       Trump Is So Obsessed He Even Has Obama’s Name...   
4       Pope Francis Just Called Out Donald Trump Dur...   
...                                                  ...   
23476  McPain: John McCain Furious That Iran Treated ...   
23477  JUSTICE? Yahoo Settles E-mail Privacy Class-ac...   
23478  Sunnistan: US and Allied ‘Safe Zone’ Plan to T...   
23479  How to Blow $700 Million: Al Jazeera America F...   
23480  10 U.S. Navy Sailors Held by Iranian Military ...   

                                                    text      subject   
0      Donald Trump just couldn t wish all Americans ...         News  \
1      House Intelligence Committee Chairman Devin Nu...         News   
2      On Friday, it was revealed that former Milwauk...         News   
3      On Christmas day, Donald Trump announced that ...         News   
4      Pope Francis used his annual Christmas Day mes...         News   
...                                                  ...          ...   
23476  21st Century Wire says As 21WIRE reported earl...  Middle-east   
23477  21st Century Wire says It s a familiar theme. ...  Middle-east   
23478  Patrick Henningsen  21st Century WireRemember ...  Middle-east   
23479  21st Century Wire says Al Jazeera America will...  Middle-east   
23480  21st Century Wire says As 21WIRE predicted in ...  Middle-east   

                    date  
0      December 31, 2017  
1      December 31, 2017  
2      December 30, 2017  
3      December 29, 2017  
4      December 25, 2017  
...                  ...  
23476   January 16, 2016  
23477   January 16, 2016  
23478   January 15, 2016  
23479   January 14, 2016  
23480   January 12, 2016  

[23481 rows x 4 columns]

In [5]:
True_news["label"]=0
Fake_news["label"]=1

In [6]:
dataset1=True_news[['text','label']]

In [7]:
dataset2=Fake_news[['text','label']]

In [8]:
dataset=pd.concat([dataset1,dataset2])

In [9]:
dataset

text  label
0      WASHINGTON (Reuters) - The head of a conservat...      0
1      WASHINGTON (Reuters) - Transgender people will...      0
2      WASHINGTON (Reuters) - The special counsel inv...      0
3      WASHINGTON (Reuters) - Trump campaign adviser ...      0
4      SEATTLE/WASHINGTON (Reuters) - President Donal...      0
...                                                  ...    ...
23476  21st Century Wire says As 21WIRE reported earl...      1
23477  21st Century Wire says It s a familiar theme. ...      1
23478  Patrick Henningsen  21st Century WireRemember ...      1
23479  21st Century Wire says Al Jazeera America will...      1
23480  21st Century Wire says As 21WIRE predicted in ...      1

[44898 rows x 2 columns]

In [10]:
dataset.shape


(44898, 2)

In [11]:
#check for null values
dataset.isnull().sum()

text     0
label    0
dtype: int64

In [12]:
dataset['label'].value_counts()

label
1    23481
0    21417
Name: count, dtype: int64

In [13]:
dataset=dataset.sample(frac=1)

In [14]:
dataset

text  label
5437   MEXICO CITY (Reuters) - U.S. Secretary of Stat...      0
20375  To hell with the common sense voter, Hillary b...      1
4986   (Reuters) - A Kansas state senator on Monday d...      0
19206  SINGAPORE (Reuters) - A Singaporean bodybuilde...      0
11716  YANGON (Reuters) - Myanmar s army said on Wedn...      0
...                                                  ...    ...
15959  What will he think of next? Is Kim Jong-un is ...      1
5484   When Bill O Reilly calls himself a journalist,...      1
18067  SABRATHA, Libya (Reuters) - An armed alliance ...      0
4082   The math for the election is very simple: The ...      1
11970  Ownage. pic.twitter.com/yznLKcYiMW  Paul Josep...      1

[44898 rows x 2 columns]

In [15]:
#nlp

In [16]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer


In [17]:
ps=WordNetLemmatizer()


In [18]:
 nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [19]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [20]:
stopwords=set(stopwords.words('english'))

In [21]:
def clean_row(row):
    row=row.lower()
    row=re.sub('[^a-zA-Z]',' ',row) # reg ex removing numbers and special characters 
    token= row.split()
    news=[ps.lemmatize(word) for word in token if not word in stopwords]
    cleaned_news=' '.join(news)
    return cleaned_news

In [22]:
dataset['text']

5437     MEXICO CITY (Reuters) - U.S. Secretary of Stat...
20375    To hell with the common sense voter, Hillary b...
4986     (Reuters) - A Kansas state senator on Monday d...
19206    SINGAPORE (Reuters) - A Singaporean bodybuilde...
11716    YANGON (Reuters) - Myanmar s army said on Wedn...
                               ...                        
15959    What will he think of next? Is Kim Jong-un is ...
5484     When Bill O Reilly calls himself a journalist,...
18067    SABRATHA, Libya (Reuters) - An armed alliance ...
4082     The math for the election is very simple: The ...
11970    Ownage. pic.twitter.com/yznLKcYiMW  Paul Josep...
Name: text, Length: 44898, dtype: object

In [23]:
dataset['text'] = dataset['text'].apply(lambda x: clean_row(x))

In [24]:
dataset['text']

5437     mexico city reuters u secretary state rex till...
20375    hell common sense voter hillary belief need am...
4986     reuters kansa state senator monday declined ba...
19206    singapore reuters singaporean bodybuilder died...
11716    yangon reuters myanmar army said wednesday app...
                               ...                        
15959    think next kim jong un preparing special force...
5484     bill reilly call journalist show idea word act...
18067    sabratha libya reuters armed alliance involved...
4082     math election simple black voter worse result ...
11970    ownage pic twitter com yznlkcyimw paul joseph ...
Name: text, Length: 44898, dtype: object

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [26]:
vectorizer=TfidfVectorizer(max_features=80000,lowercase=False,ngram_range=(1,2))

In [27]:
x=dataset.iloc[:35000,0]
y=dataset.iloc[:35000,1]


In [28]:
x


5437     mexico city reuters u secretary state rex till...
20375    hell common sense voter hillary belief need am...
4986     reuters kansa state senator monday declined ba...
19206    singapore reuters singaporean bodybuilder died...
11716    yangon reuters myanmar army said wednesday app...
                               ...                        
1319     washington reuters u house representative spea...
775      reuters peace activist laughed u senator jeff ...
12329    london reuters britain le likely leave europea...
9579     washington reuters presumptive republican pres...
3840     america fascist white house starting january t...
Name: text, Length: 35000, dtype: object

In [29]:
y

5437     0
20375    1
4986     0
19206    0
11716    0
        ..
1319     0
775      0
12329    0
9579     0
3840     1
Name: label, Length: 35000, dtype: int64

In [30]:
from sklearn.model_selection import train_test_split


In [31]:
train_data,test_data,train_label,test_label=train_test_split(x,y,test_size=0.15,random_state=0)

In [32]:
vec_train_data = vectorizer.fit(train_data)


In [33]:
vec_train_data=vectorizer.transform(train_data)

In [34]:
type(vec_train_data)

scipy.sparse._csr.csr_matrix

In [35]:
vec_train_data=vec_train_data.toarray()

In [36]:
vec_test_data=vectorizer.fit(test_data)
vec_test_data=vectorizer.transform(test_data)
vec_test_data=vec_test_data.toarray()

In [37]:
vec_test_data

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [38]:
vec_train_data

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [39]:
train_data = pd.DataFrame(vec_train_data, columns=vectorizer.get_feature_names_out())
testing_data= pd.DataFrame(vec_test_data, columns=vectorizer.get_feature_names_out())

In [40]:
vec_train_data.shape,vec_test_data.shape

((29750, 80000), (5250, 80000))

In [41]:
train_data

aa  aaa  aadhaar  aadhaar holder  aapl  aaron  aaron bernstein   
0      0.0  0.0      0.0             0.0   0.0    0.0              0.0  \
1      0.0  0.0      0.0             0.0   0.0    0.0              0.0   
2      0.0  0.0      0.0             0.0   0.0    0.0              0.0   
3      0.0  0.0      0.0             0.0   0.0    0.0              0.0   
4      0.0  0.0      0.0             0.0   0.0    0.0              0.0   
...    ...  ...      ...             ...   ...    ...              ...   
29745  0.0  0.0      0.0             0.0   0.0    0.0              0.0   
29746  0.0  0.0      0.0             0.0   0.0    0.0              0.0   
29747  0.0  0.0      0.0             0.0   0.0    0.0              0.0   
29748  0.0  0.0      0.0             0.0   0.0    0.0              0.0   
29749  0.0  0.0      0.0             0.0   0.0    0.0              0.0   

       aaron klein  aarp   ab  ...  zpzgvvx dwrpby  zsqbk  zsqbk nv   
0              0.0   0.0  0.0  ...             0.0    0.0       0.0  \
1              0.0   0.0  0.0  ...             0.0    0.0       0.0   
2              0.0   0.0  0.0  ...             0.0    0.0       0.0   
3              0.0   0.0  0.0  ...             0.0    0.0       0.0   
4              0.0   0.0  0.0  ...             0.0    0.0       0.0   
...            ...   ...  ...  ...             ...    ...       ...   
29745          0.0   0.0  0.0  ...             0.0    0.0       0.0   
29746          0.0   0.0  0.0  ...             0.0    0.0       0.0   
29747          0.0   0.0  0.0  ...             0.0    0.0       0.0   
29748          0.0   0.0  0.0  ...             0.0    0.0       0.0   
29749          0.0   0.0  0.0  ...             0.0    0.0       0.0   

       zuckerberg  zuckerberg said  zulia  zullo  zuma  zuma said  zuma told  
0             0.0              0.0    0.0    0.0   0.0        0.0        0.0  
1             0.0              0.0    0.0    0.0   0.0        0.0        0.0  
2             0.0              0.0    0.0    0.0   0.0        0.0        0.0  
3             0.0              0.0    0.0    0.0   0.0        0.0        0.0  
4             0.0              0.0    0.0    0.0   0.0        0.0        0.0  
...           ...              ...    ...    ...   ...        ...        ...  
29745         0.0              0.0    0.0    0.0   0.0        0.0        0.0  
29746         0.0              0.0    0.0    0.0   0.0        0.0        0.0  
29747         0.0              0.0    0.0    0.0   0.0        0.0        0.0  
29748         0.0              0.0    0.0    0.0   0.0        0.0        0.0  
29749         0.0              0.0    0.0    0.0   0.0        0.0        0.0  

[29750 rows x 80000 columns]

In [42]:
#model
from sklearn.naive_bayes import MultinomialNB 

In [43]:
clf = MultinomialNB()

In [44]:
clf.fit(train_data,train_label)

MultinomialNB()

In [45]:
y_pred=clf.predict(testing_data)

In [46]:
test_label

3636     1
13833    0
3911     1
3779     1
9302     0
        ..
17118    0
4642     0
2093     0
17257    0
8068     1
Name: label, Length: 5250, dtype: int64

In [47]:
y_pred

array([0, 1, 0, ..., 1, 1, 1], dtype=int64)

In [48]:
from sklearn.metrics import accuracy_score

In [49]:
accuracy_score(test_label,y_pred)

0.7011428571428572

In [ ]:
#TESTING

In [53]:
txt = 'Alert!!! Donald Trump died today click here'

In [54]:
news=clean_row(txt)

In [55]:
news

'alert donald trump died today click'

In [56]:
pred=clf.predict(vectorizer.transform([news]).toarray())

C:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(


In [57]:
pred

array([1], dtype=int64)

In [58]:
if pred==0:
    print('News is True');
else:
    print('News is False');


News is False


In [62]:
txt=input('Enter News: ')
news=clean_row(str(txt))
pred=clf.predict(vectorizer.transform([news]).toarray())

Enter News: WASHINGTON (Reuters) - The special counsel investigation of links between Russia and President Trump’s 2016 election campaign should continue without interference in 2018, despite calls from some Trump administration allies and Republican lawmakers to shut it down, a prominent Republican senator said on Sunday. Lindsey Graham, who serves on the Senate armed forces and judiciary committees, said Department of Justice Special Counsel Robert Mueller needs to carry on with his Russia investigation without political interference. “This investigation will go forward. It will be an investigation conducted without political influence,” Graham said on CBS’s Face the Nation news program. “And we all need to let Mr. Mueller do his job. I think he’s the right guy at the right time.”  The question of how Russia may have interfered in the election, and how Trump’s campaign may have had links with or co-ordinated any such effort, has loomed over the White House since Trump

C:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(


In [63]:
if pred==0:
    print('News is True');
else:
    print('News is False');

News is True
